allowBuilds:
  '@nestjs/core': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  sharp: true
minimumReleaseAgeExclude:
  - '@types/node@25.9.1'
  - isomorphic-dompurify@3.14.0
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - esbuild
  - msgpackr-extract
  - sharp
