allowBuilds:
  '@nestjs/core': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  sharp: true
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - esbuild
  - msgpackr-extract
  - sharp
