allowBuilds:
  '@nestjs/core': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  sharp: true
overrides:
  lodash: '>=4.18.1'
minimumReleaseAgeExclude:
  - '@types/node@25.9.1'
  - isomorphic-dompurify@3.14.0
